name: EBanking CI Tests & Report

on:
  push:
    branches: ["master", "develop"]
  pull_request:
    branches: ["master", "develop"]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4

      - name: 2. Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: 3. Setup Browser Drivers
        uses: browser-actions/setup-chrome@v1
      - name: 3. Setup Browser Drivers
        uses: browser-actions/setup-firefox@v1

      - name: 4. Run Tests in Headless Mode
        run: mvn clean test -Dheadless=true

      - name: 5. Generate Allure Report
        if: always()
        uses: allure-framework/allure-action@v2
        with:
            allure_results_dir: target/allure-results
            install_allure: true
      - name: 6. Publish Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          keep_files: true